name: build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Test stuff
        run: mvn test

# uncoment this line once public - this way we save the hassle of Codecov PAT token configuration
#      - name: Publish test coverage
#        uses: codecov/codecov-action@v1