name: Geoscan Release

env:
  LABS_GITHUB_TOKEN: ${{ secrets.LABS_GITHUB_TOKEN }}
  LABS_DEPLOY_USERNAME: ${{ secrets.LABS_DEPLOY_USERNAME }}
  LABS_DEPLOY_PASSWORD: ${{ secrets.LABS_DEPLOY_PASSWORD }}
  LABS_GPG_PRIVATE_KEY: ${{ secrets.LABS_GPG_PRIVATE_KEY }}
  LABS_GPG_PASSPHRASE: ${{ secrets.LABS_GPG_PASSPHRASE }}
  LABS_PYPI_TOKEN: ${{ secrets.LABS_PYPI_TOKEN }}
  MAVEN_OPTS: -Xmx4g

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "New release version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: LABS_GITHUB_TOKEN

      - name: Configure git
        run: |
          git config --global user.email "antoine.amend+labs@databricks.com"
          git config --global user.name "Databrickslabs"

      - name: Set up Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          server-id: ossrh
          server-username: LABS_DEPLOY_USERNAME
          server-password: LABS_DEPLOY_PASSWORD
          gpg-private-key: LABS_GPG_PRIVATE_KEY
          gpg-passphrase: LABS_GPG_PASSPHRASE

      - name: Compute next development version
        run: |
          releaseVersion=${{ github.event.inputs.releaseVersion }}
          n=${releaseVersion//[!0-9]/ }
          a=(${n//\./ })
          nextPatch=$((${a[2]} + 1))
          developmentVersion="${a[0]}.${a[1]}.${nextPatch}-SNAPSHOT"
          echo "DEVELOPMENT_VERSION=${developmentVersion}" >> $GITHUB_ENV

      - name: Prepare release
        run: mvn -B -DpreparationGoals=clean release:prepare -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ env.DEVELOPMENT_VERSION }} -P release

      - name: Perform release
        run: mvn -B release:perform -P release

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Cache pip repo
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: ./python
        run: pip install -U -r requirements.txt

      - name: Build python dist
        working-directory: ./python
        run: python setup.py clean bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: LABS_PYPI_TOKEN
          packages_dir: dist/
